//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 12/28/2015 12:04:19 AM

#ifndef __gcmResource_h__
#define __gcmResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:gcmResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HIMALAYA 28
#define REF_FNA_LCD 1095
#define REF_FNA_DOS 2162
#define REF_FNA_PRIMO 4989
#define REF_FNA_LEROS 6875
#define REF_FNA_NICE_MONO 9798

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x47525453 (string)
#define REF_MNU_FAST_CASSETTE 12785
#define REF_MNU_FULL_SPEED_EMULATION 12804
#define REF_MNU_ENABLED 12820
#define REF_MNU_DISABLED 12827

#endif

