//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 12/28/2015 11:01:06 PM

#ifndef __sysResource_h__
#define __sysResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:sysResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_ARROW_LEFT 36
#define REF_BMP_ARROW_RIGHT 49

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HIMALAYA 62
#define REF_FNA_LCD 1129
#define REF_FNA_DOS 2196
#define REF_FNA_PRIMO 5023
#define REF_FNA_LEROS 6909
#define REF_FNA_NICE_MONO 9832

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x47525453 (string)
#define REF_MNU_FAST_CASSETTE 12819
#define REF_MNU_FULL_SPEED_EMULATION 12838
#define REF_MNU_ENABLED 12854
#define REF_MNU_DISABLED 12861

#endif

