//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 7/26/2015 7:52:24 PM

#ifndef __sysResource_h__
#define __sysResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:fbResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_FILE 28
#define REF_BMP_AUDIO 49
#define REF_BMP_MUSIC 70
#define REF_BMP_UP 91
#define REF_BMP_FOLDER 112
#define REF_BMP_PROGRESS1 133
#define REF_BMP_PROGRESS2 1162
#define REF_BMP_PROGRESS3 3215
#define REF_BMP_PROGRESS4 5268
#define REF_BMP_PROGRESS5 7321
#define REF_BMP_PROGRESS6 9374
#define REF_BMP_PROGRESS7 11427
#define REF_BMP_PROGRESS8 13480
#define REF_BMP_PROGRESS9 15533
#define REF_BMP_PROGRESS10 17586
#define REF_BMP_PROGRESS11 19639
#define REF_BMP_PROGRESS12 21692
#define REF_BMP_PROGRESS13 23745
#define REF_BMP_PROGRESS14 25798
#define REF_BMP_PROGRESS15 27851
#define REF_BMP_PROGRESS16 29904
#define REF_BMP_PROGRESS17 31957
#define REF_BMP_PROGRESS18 34010
#define REF_BMP_PROGRESS19 36063
#define REF_BMP_PROGRESS20 38116
#define REF_BMP_PROGRESS21 40169
#define REF_BMP_PROGRESS22 42222
#define REF_BMP_PROGRESS23 44275
#define REF_BMP_PROGRESS24 46328
#define REF_BMP_PROGRESS25 48381
#define REF_BMP_PROGRESS26 50434
#define REF_BMP_PROGRESS27 52487
#define REF_BMP_PROGRESS28 54540
#define REF_BMP_PROGRESS29 56593
#define REF_BMP_PROGRESS30 58646
#define REF_BMP_PROGRESS31 60699

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HIMALAYA 62752
#define REF_FNA_LCD 63819
#define REF_FNA_DOS 64886
#define REF_FNA_SIMPLE 67713
#define REF_FNA_PRIMO 68780
#define REF_FNA_LEROS 70666
#define REF_FNA_NICE_MONO 73589

#endif

