//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 8/27/2015 3:04:20 PM

#ifndef __emuInvadersResource_h__
#define __emuInvadersResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:emuInvadersResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x45564157 (wave)
#define REF_WAV_BASE_HIT 28
#define REF_WAV_INV_HIT 6581
#define REF_WAV_SHOT 10666
#define REF_WAV_UFO 14048
#define REF_WAV_UFO_HIT 15855
#define REF_WAV_WALK1 41665
#define REF_WAV_WALK2 42703
#define REF_WAV_WALK3 43702
#define REF_WAV_WALK4 44703

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_BACKGROUND 45665

#endif

