//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 1/4/2016 10:48:23 AM

#ifndef __sysResource_h__
#define __sysResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:sysResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_ARROW_LEFT 36
#define REF_BMP_ARROW_RIGHT 53
#define REF_BMP_FILE 70
#define REF_BMP_CASSETTE 99
#define REF_BMP_UP 128
#define REF_BMP_FOLDER 157
#define REF_BMP_PROGRESS0 186
#define REF_BMP_PROGRESS1 248
#define REF_BMP_PROGRESS2 310
#define REF_BMP_PROGRESS3 372
#define REF_BMP_PROGRESS4 434
#define REF_BMP_PROGRESS5 496
#define REF_BMP_PROGRESS6 558
#define REF_BMP_PROGRESS7 620

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HT1080 682
#define REF_FNA_HIMALAYA 2613
#define REF_FNA_LCD 3680
#define REF_FNA_DOS 4747
#define REF_FNA_PRIMO 7574
#define REF_FNA_LEROS 9460
#define REF_FNA_NICE_MONO 12383

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x47525453 (string)
#define REF_MNU_TITLE 15370
#define REF_MNU_FAST_CASSETTE 15393
#define REF_MNU_FULL_SPEED_EMULATION 15412
#define REF_MNU_SHOW_EMULATION_STATISTICS 15428
#define REF_MNU_ENABLED 15449
#define REF_MNU_DISABLED 15456
#define REF_MNU_HIDE 15461
#define REF_MNU_SHOW 15466

#endif

