//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 1/2/2016 11:34:23 PM

#ifndef __sysResource_h__
#define __sysResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:sysResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_ARROW_LEFT 36
#define REF_BMP_ARROW_RIGHT 53
#define REF_BMP_FILE 70
#define REF_BMP_AUDIO 91
#define REF_BMP_MUSIC 112
#define REF_BMP_UP 133
#define REF_BMP_FOLDER 154
#define REF_BMP_PROGRESS0 175
#define REF_BMP_PROGRESS1 237
#define REF_BMP_PROGRESS2 299
#define REF_BMP_PROGRESS3 361
#define REF_BMP_PROGRESS4 423
#define REF_BMP_PROGRESS5 485
#define REF_BMP_PROGRESS6 547
#define REF_BMP_PROGRESS7 609

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HT1080 671
#define REF_FNA_HIMALAYA 2602
#define REF_FNA_LCD 3669
#define REF_FNA_DOS 4736
#define REF_FNA_PRIMO 7563
#define REF_FNA_LEROS 9449
#define REF_FNA_NICE_MONO 12372

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x47525453 (string)
#define REF_MNU_TITLE 15359
#define REF_MNU_FAST_CASSETTE 15382
#define REF_MNU_FULL_SPEED_EMULATION 15401
#define REF_MNU_SHOW_EMULATION_STATISTICS 15417
#define REF_MNU_ENABLED 15438
#define REF_MNU_DISABLED 15445
#define REF_MNU_HIDE 15450
#define REF_MNU_SHOW 15455

#endif

