//#cdecl
///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the Domino OS Resource Linker
// at 8/19/2015 3:43:46 PM

#ifndef __fbResource_h__
#define __fbResource_h__

// Parameters
//#addressmode:absolute
//#outputfile:fbResource.c

#define PAR_ADDRESS_ABSOLUTE


///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x53504d42 (bitmap)
#define REF_BMP_FILE 28
#define REF_BMP_AUDIO 49
#define REF_BMP_MUSIC 70
#define REF_BMP_UP 91
#define REF_BMP_FOLDER 112
#define REF_BMP_PROGRESS0 133
#define REF_BMP_PROGRESS1 195
#define REF_BMP_PROGRESS2 257
#define REF_BMP_PROGRESS3 319
#define REF_BMP_PROGRESS4 381
#define REF_BMP_PROGRESS5 443
#define REF_BMP_PROGRESS6 505
#define REF_BMP_PROGRESS7 567

///////////////////////////////////////////////////////////////////////////////
//#chunkid:0x544e4f46 (font)
#define REF_FNA_HIMALAYA 629
#define REF_FNA_LCD 1696
#define REF_FNA_DOS 2763
#define REF_FNA_SIMPLE 5590
#define REF_FNA_PRIMO 6657
#define REF_FNA_LEROS 8543
#define REF_FNA_NICE_MONO 11466

#endif

